version: 2.1
jobs:
  norminette_tests:
    docker:
      - image: salemribeiro/42tests_salem:1.4
    steps:
      - checkout
      - run: norme.sh ~/project/
      - run: norme.sh ~/project/sources/
      - run: norme.sh ~/project/sources/gnl/
      - run: norme.sh ~/project/sources/libft/
      - run: norme.sh ~/project/sources/ft_printf/sources/
      - run: norme.sh ~/project/sources/ft_printf/headers/
  wrong_maps_tests:
    docker:
      - image: salemribeiro/42tests_salem:1.4
    steps:
      - checkout
      - run: cd ~/project/ && make
      - run: maps.sh ~/project/cub3D ~/project/tests/err_maps/map_2_players.cub 14
  correct_maps_tests:
    docker:
      - image: salemribeiro/42tests_salem:1.4
    steps:
      - checkout
      - run: cd ~/project/ && make
      - run: maps.sh ~/project/cub3D ~/project/tests/maps/cub3d.cub 0
workflows:
  version: 2.1
  test_norme:
    jobs:
      - norminette_tests
      - wrong_maps_tests
      - correct_maps_tests
