version: 2.1
jobs:
  norminette:
    docker: 
      - image: ubuntu:20.04
    steps:
      - checkout
      - run: apt update -y && apt upgrade -y
      - run: apt install make clang git ruby ruby-bundler ruby-dev build-essential -y
      - run: git clone https://github.com/42Paris/norminette.git ~/.norminette/
      - run: cd ~/.norminette/ && bundle
      - run: echo 'alias norminette="~/.norminette/norminette.rb"' >> ~/.bashrc
      - run: source ~/.bashrc       
workflows:
  version: 2.1
  test_nome:
    jobs:
      - norminette
