version: 2.1
jobs:
  tests:
    docker: 
      - image: salemribeiro/42tests_salem:1.2
    steps:
      - checkout
      - run: norme.sh ~/project/
  qa:
    docker: 
        - image: salemribeiro/42tests_salem:latest
    steps:
      - run: git checkout main && git merge qa
      
workflows:
  version: 2.1
  test_norme:
    jobs:
      - tests
  
  
