version: 2.1
jobs:
  tests:
    working_directory: ~/project
    docker: 
      - image: salemribeiro/42tests_salem:latest
    steps:
      - checkout
      - run: cd scipts
      - run: ./norme.sh ../
  qa:
    docker: 
        - image: salemribeiro/42tests_salem:latest
    steps:
      - run: git checkout main && git merge qa
      
workflows:
  version: 2.1
  test_norme:
    jobs:
      - tests
  
  
